import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import { Navbar } from "components/";

const quicksand = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Oh My Cookies | Your Recipe App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={quicksand.className}>
        <main className="min-w-screen min-h-screen flex flex-row">
          <aside className="fixed h-full w-[108px]">
            <Navbar />
          </aside>
          <section className="pl-[108px] h-full w-full">{children}</section>
        </main>
      </body>
    </html>
  );
}

